name: Sync

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  ryu-cho:
    name: Ryu Cho
    runs-on: ubuntu-latest
    steps:
      - uses: vuejs-translations/ryu-cho@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          username: github-actions
          email: "action@github.com"

          upstream-repo: https://github.com/yhchoo/docs-ko.git
          upstream-repo-branch: main

          head-repo: https://github.com/vitejs/vite
          head-repo-branch: main
          track-from: 0cbd81895ecb462f93b4cb9522576b305f984f3f
          path-starts-with: docs/
          workflow-name: ryu-cho
